### ISSUE TITLE
Website parsen anstatt API verwenden?

### ISSUE THREAD

**Issue by timohenz** [msw-projects/finanzterminbot#1]
Sehe ich das richtig, dass die Termine einfach per 'https://www.finanzen.net/termine/termine_suchergebnis.asp' von der Website über den hardcodierten Pfad ```dom.xpath('/html/body/div[2]/div[1]/div[2]/div[9]/div[1]/div[1]/div[1]/h2/text()')[0].strip() ```
gescraped werden?

Das ist doch komplizierter und instabiler als einfach eine api zu benutzen, wie es für praw auch gemacht wurde?

**Comment by flxn** [comment]
Da hast du vollkommen recht, allerdings haben wir keine kostenlose API gefunden die uns diese Daten liefert.
Wenn du eine API dafür kennst, dann können wir die sehr gerne einbauen.
